kind: MachineConfig
apiVersion: machineconfiguration.openshift.io/v1
metadata:
  name: 99-akraino-sec-worker
  creationTimestamp:
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - filesystem: root
        path: "/root/akrainosec.sh"
        contents:
          source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKc3VkbyBzeXNjdGwgLXcga2VybmVsLmRtZXNnX3Jlc3RyaWN0PTEKc3VkbyBzeXNjdGwgLXcgbmV0LmlwdjQuY29uZi5kZWZhdWx0LmFjY2VwdF9zb3VyY2Vfcm91dGU9MApzdWRvIHNlZCAtaSAnL15QQVNTX01BWF9EQVlTL2NcUEFTU19NQVhfREFZUyAgIDk5OCcgL2V0Yy9sb2dpbi5kZWZzCnN1ZG8gZWNobyAiQWxsb3dVc2VycyBjb3JlIiA+PiAvZXRjL3NzaC9zc2hkX2NvbmZpZwpzdWRvIGVjaG8gIkFsbG93R3JvdXBzIGNvcmUiID4+IC9ldGMvc3NoL3NzaGRfY29uZmlnCnN1ZG8gc2VkIC1pICdzL14gICAgdW1hc2suKi8gICAgdW1hc2sgMDI3L2cnIC9ldGMvcHJvZmlsZQ==
          verification: {}
        mode: 0755
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Akraino Security
            DefaultDependencies=no
            [Service]
            Type=oneshot
            ExecStart=/bin/bash /root/akrainosec.sh
            Restart=on-failure
            RestartSec=30
            [Install]
            WantedBy=multi-user.target
          name: akrainosec.service
          enabled: true
